server:
  ssl:
    enabled: false
#    key-store: classpath:service-b.p12
#    key-store: src/main/resources/keystore/service-b.p12
#    key-store-password: secret123
#    key-alias: service-b
  sni-host-check: false

client:
  ssl:
    key-store: classpath:service-b.p12
    key-store-password: secret123
    key-store-type: PKCS12
    trust-store: classpath:service-b-truststore.p12
    trust-store-password: secret123
    trust-store-type: PKCS12
    enabled: false

spring:
  application:
    name: soa_service_b

  r2dbc:
    enabled: false

  data:
    r2dbc:
      repositories:
        enabled: false

#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
#      - org.springframework.boot.autoconfigure.data.r2dbc.R2dbcDataAutoConfiguration
#      - org.springframework.boot.autoconfigure.data.r2dbc.R2dbcRepositoriesAutoConfiguration
#      - org.springdoc.webmvc.ui.SwaggerConfig
#      - org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
#      # Отключаем автоконфигурации встроенного веб-сервера (ВАЖНО!)
#      - org.springframework.boot.autoconfigure.web.servlet.ServletWebServerFactoryAutoConfiguration
#      - org.springframework.boot.autoconfigure.web.embedded.EmbeddedWebServerFactoryCustomizerAutoConfiguration

service:
  a:
    base-url: https://localhost:8218